name: Deployment
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.16.1]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install yarn
        run: npm install yarn -g
      - name: Install PlantUML
        run: sudo apt-get install plantuml
      - name: Install Packages
        run: yarn install
      - name: Build diagrams
        run: make -C diagrams
      - name: Build page
        run: yarn run build
